version: '3.1'

volumes:
  barber_project:
  minio_storage:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=barber_db
    volumes:
      - barber_project:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    restart: always
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    volumes:
      - minio_storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - pg_db
      - minio
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://pg_db:5432/barber_db'
      S3_ENDPOINT: 'http://minio:9000/'
      JAVA_OPTS: '-Xmx512m'