package kz.azamatbakyt.BarberTelegramBot.helpers;

public enum CallbackType {
    SERVICE,
    SERVICE_GROUP,
    TIMESLOT,
    YES_FOR_CREATING_APPOINTMENT,
    NO_FOR_CREATING_APPOINTMENT,
    CHOOSE_TIMESLOT,
    MAKE_APPOINTMENT,
    CONFIRM_APPOINTMENT,
    DO_NOT_CONFIRM_APPOINTMENT
}
