package kz.azamatbakyt.BarberTelegramBot.helpers;

public enum ContentType {
    SERVICE,
    SERVICE_GROUP,
    TIMESLOT,
    YES_FOR_CREATING_APPOINTMENT,
    CHOOSE_TIMESLOT,
    MAKE_APPOINTMENT,
    CONFIRM_APPOINTMENT,
    APPOINTMENT_CREATED,
    CANCEL_ACTION,
    VIEW_APPOINTMENT,
    DELETED_APPOINTMENT
}
