package kz.azamatbakyt.BarberTelegramBot.service.bot.callback;

public enum CallbackType {

    SERVICES,
    SERVICE_AGREE,
    YES_CREATE_SERVICE,
    NO_CANCEL_ACTION,
    DATE,
    TIMESLOTS,
    APPOINTMENT_CREATED,
    DATE_CANCELED,
    TIMESLOT_CANCELED,
    APPOINTMENT_NOT_CREATED,
    VIEW_APPOINTMENT,
    DELETED_APPOINTMENT,
    EMPTY_TIMESLOTS,
    APPOINTMENT_ID,
    ACTIVE_APPOINTMENT_DELETED,
    NOT_FINISHED_APPOINTMENT,
    DELETE_NOT_FINISHED_APPOINTMENT
}
